package com.example.practicetimestables.ui.theme

import androidx.compose.ui.graphics.Color

// Product palette: blue-violet learning focus, teal action, and warm gold reward.
val LearningBlue = Color(0xFF4147B8)
val OnLearningBlue = Color(0xFFFFFFFF)
val LearningBlueContainer = Color(0xFFE4E7FF)
val OnLearningBlueContainer = Color(0xFF202A72)

val ActionTeal = Color(0xFF009D91)
val OnActionTeal = Color(0xFFFFFFFF)
val ActionTealContainer = Color(0xFFC5F0EA)
val OnActionTealContainer = Color(0xFF004F49)

val CelebrationGold = Color(0xFFD89400)
val OnCelebrationGold = Color(0xFFFFFFFF)
val CelebrationGoldContainer = Color(0xFFFFE2AC)
val OnCelebrationGoldContainer = Color(0xFF573900)

val WarmBackground = Color(0xFFF8FAFF)
val WarmSurface = Color(0xFFFFFCF8)
val PaleCream = Color(0xFFFFF5E8)
val PaleLavender = Color(0xFFF1EEFF)
val PaleBlue = Color(0xFFEDF2FF)
val PaleAqua = Color(0xFFE5F8F5)
val WarmSurfaceVariant = Color(0xFFE8ECFA)
val DeepNavyInk = Color(0xFF1D2440)
val MutedSlateInk = Color(0xFF4D5575)
val SoftOutline = Color(0xFFBCC6E8)
val WarmError = Color(0xFFB3263E)
val SuccessGreen = Color(0xFF24734F)

val LearningBlueDark = Color(0xFFC0C5FF)
val OnLearningBlueDark = Color(0xFF18226D)
val LearningBlueContainerDark = Color(0xFF303C9A)
val OnLearningBlueContainerDark = Color(0xFFE2E4FF)
val ActionTealDark = Color(0xFF76D8CE)
val OnActionTealDark = Color(0xFF003732)
val ActionTealContainerDark = Color(0xFF005049)
val OnActionTealContainerDark = Color(0xFFA7F2E9)
val CelebrationGoldDark = Color(0xFFFFC96F)
val OnCelebrationGoldDark = Color(0xFF452B00)
val CelebrationGoldContainerDark = Color(0xFF654600)
val OnCelebrationGoldContainerDark = Color(0xFFFFDEA0)
val DarkBackground = Color(0xFF181A22)
val DarkSurface = Color(0xFF1E2029)
val DarkSurfaceVariant = Color(0xFF2A2D38)
val DarkSurfaceLow = Color(0xFF222631)
val DarkSurfaceContainer = Color(0xFF272B38)
val DarkSurfaceHigh = Color(0xFF303545)
val DarkInk = Color(0xFFE7E5ED)
val DarkMutedInk = Color(0xFFC7C5D0)
val DarkOutline = Color(0xFF474A57)
val WarmErrorDark = Color(0xFFFFB3BC)
val SuccessGreenDark = Color(0xFF86D7AB)
